version: "3"

services:
    s3:
        image: minio/minio:edge
        ports:
            - '9000:9000'
        command: server /home/s3
        networks:
            - sauna-booker-network
        environment:
            - MINIO_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
            - MINIO_SECRET_KEY=${AWS_S3_ACCESS_SECRET}
        volumes:
            - ./data/s3:/home/s3/

    sauna-booker-bucket:
        image: minio/mc
        depends_on:
            - s3
        networks:
            - sauna-booker-network
        entrypoint: >
            /bin/sh -c "
            until /usr/bin/mc config host add s3 http://s3:9000 ${AWS_S3_ACCESS_KEY} ${AWS_S3_ACCESS_SECRET};
            do echo 'Minio is unavailable - sleeping'; 
            sleep 1; 
            done;
            /usr/bin/mc mb s3/${AWS_S3_BUCKET};
            /usr/bin/mc policy set download s3/${AWS_S3_BUCKET};
            exit 0;
            "

networks:
    sauna-booker-network:
