app: sauna-booker
service: sauna-booker
frameworkVersion: ^2.33.1
disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_S3_REGION}
  stackTags:
    Owner: Olli Saarinen
    Project: sauna-booker-${opt:stage}
  environment:
    AWS_S3_URL: !Join ['', ['https://', !GetAtt ["BookingErrorBucket", "DomainName"]]]
    AWS_S3_ACCESS_KEY: !Ref S3UserAccessKey
    AWS_S3_ACCESS_SECRET: !GetAtt ["S3UserAccessKey", "SecretAccessKey"]
    AWS_S3_BUCKET: !Ref BookingErrorBucket
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: BookingErrorBucket
                - '/*'


package:
  exclude:
    - .env.dev
    - .env.local
    - data

functions:
  book-sauna:
    handler: app/handler.bookSauna
    timeout: 500
    # Extending Lambda layer
    layers:
        - arn:aws:lambda:${env:AWS_S3_REGION}:764866452798:layer:chrome-aws-lambda:22
    events:
      - schedule:
          # Helsinki timezone is UTC+2|3. 
          # This UTC trigger will run 00.01 or 1.01 in Helsinki every day
          rate: cron(1,30 21-22,1 ? * MON-SUN *)  
          enabled: true
          input:
            ignoreMidnight: false


custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

# AWS cloudformation resources
resources:

  Conditions:
    IsProd: !Equals ["${opt:stage}", "prod"]

  Resources:
    BookingErrorBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${opt:stage}-sauna-booking-error-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True

    S3User:
      Type: AWS::IAM::User
      Properties:
        Policies:
          - PolicyName: bucket-access
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${BookingErrorBucket}
                  - !Sub arn:aws:s3:::${BookingErrorBucket}/*

    S3UserAccessKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName: !Ref S3User
