app: sauna-booker
service: sauna-booker
frameworkVersion: ^2.33.1
disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_S3_REGION}
  stackTags:
    Owner: Olli Saarinen
    Project: sauna-booker-${opt:stage}
  environment:


package:
  exclude:
    - .env.dev

functions:
  book-sauna:
    handler: app/handler.bookSauna
    timeout: 500
    # Extending Lambda layer
    layers:
        - arn:aws:lambda:${env:AWS_S3_REGION}:764866452798:layer:chrome-aws-lambda:22
    events:
      - schedule:
          # Helsinki timezone is UTC+2|3. 
          # This UTC trigger will run 00.01 or 1.01 in Helsinki on FRI or SUN
          # TODO Add configs to trigger every day -> configs from json
          rate: cron(0 21-22 ? * MON-SUN *)  
          enabled: true
          input:
            ignoreMidnight: false


custom:
  # Local development
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
