# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sauna Booker CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install deps
      run: npm ci
      
    - name: Run build
      run: npm run build
      
    - name: Run lint
      run: npm run lint
      

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

      - name: Create env file for secrets
        run: |
          touch .env
          echo BOOKING_USERNAME=${{ secrets.BOOKING_USERNAME }} >> .env
          echo BOOKING_PASSWORD=${{ secrets.BOOKING_PASSWORD }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          cat .env

      - name: Install deps
        run: npm ci

      - name: Deploy serverless stack
        run: sls deploy --stage prod